### 1️⃣ Cadastrar um aluno (POST)
POST http://localhost:8080/alunos
Content-Type: application/json

{
  "cpf": "12345678900",
  "nome": "Caio Santana"
}

### 1.1️⃣ Cadastrar um aluno com nome vazio (POST)
POST http://localhost:8080/alunos
Content-Type: application/json


{
  "cpf": "123",   
  "nome": ""
}


### 1.1️⃣ Cadastrar um aluno com CPF inválido (POST)
POST http://localhost:8080/alunos
Content-Type: application/json

{
  "nome": "",
  "cpf": "123"
}



###

### 2️⃣ Cadastrar outro aluno (POST)
POST http://localhost:8080/alunos
Content-Type: application/json

{
  "cpf": "98765432100",
  "nome": "Maria Oliveira"
}

###

### 3️⃣ Listar todos os alunos (GET)
GET http://localhost:8080/alunos


### 4️⃣ Cadastrar um administrador (POST)
POST http://localhost:8080/administradores
Content-Type: application/json

{
  "cpf": "11122233344",
  "nome": "Admin Teste"
}

### cadastrar um administrador com CPF inválido (POST)
POST http://localhost:8080/administradores
Content-Type: application/json

{
  "cpf": "123",   
  "nome": "Admin Inválido"
}


### cadastrar um administrador com nome vazio (POST)
POST http://localhost:8080/administradores
Content-Type: application/json

{
  "cpf": "12345678901",   
  "nome": ""
}


### 5️⃣ Cadastrar outro administrador (POST)
POST http://localhost:8080/administradores
Content-Type: application/json

{
  "cpf": "55566677788",
  "nome": "Admin Dois"
}

### 6️⃣ Listar todos os administradores (GET)
GET http://localhost:8080/administradores


### Criar uma nova intenção de presença
POST http://localhost:8080/intencoes
Content-Type: application/json

{
  
  "cpf": "12345678900",
  "dataHora": "2025-09-10T10:30:00"


}


### Criar uma nova intenção de presença
POST http://localhost:8080/intencoes
Content-Type: application/json

{
  "cpf": "98765432100",
  "dataHora": "2025-09-10T11:30:00"
}


### criar um intenção de presença com data/hora no passado
POST http://localhost:8080/intencoes
Content-Type: application/json
{
  
  "cpf": "12345678900",
  "dataHora": "2020-09-10T10:30:00"
}


### Listar todas as intenções
GET http://localhost:8080/intencoes


### Criar uma presença
POST http://localhost:8080/presencas
Content-Type: application/json

{
  "cpf": "12345678900",
  "status": "CONFIRMADA",
  "dataHora": "2025-09-12T14:10:00"
}

### Criar outra presença

POST http://localhost:8080/presencas
Content-Type: application/json

{
  "cpf": "12345678900",
  "status": "CONFIRMADA"
}


### Criar mais uma presença

POST http://localhost:8080/presencas
Content-Type: application/json

{
  "cpf": "98765432100",
  "status": "CONFIRMADA"
}

### cria presença com CPF inválido
POST http://localhost:8080/presencas
Content-Type: application/json

{
  "cpf": "123",   
  "status": "CONFIRMADA"
}


### Listar todas as presenças
GET http://localhost:8080/presencas


### Obter lotação em tempo real
GET http://localhost:8080/presencas/lotacao-tempo-real
